namespace: external

replicaCount: 1

prometheusPort: 10254

image:
  repository: ghcr.io/winnix/web-app
  tag: "main"
  pullPolicy: Always
  pullSecretName: ghcr-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 9000
  protocol: "TCP"

ingress:
  host: "localhost"